allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@marianmeres/design-tokens@1.5.1'
  - '@marianmeres/design-tokens@1.6.0'
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
