<script lang="ts">
	// prettier-ignore
	let links = [
		'accordion',
		'alert-confirm-prompt',
		'animated-ellipsis',
		'auto-height',
		'avatar',
		'app-shell',
		'app-shell-simple', 
		'assets-preview', 
		// 'avatar', 
		'backdrop',
		'breadcrumbs',
        'button',
        'button-group-radio', 
		'carousel', 
		'card',
		'cart',
		'checkout',
		'collapsible', 
        'color-scheme', 
		'command-menu',
		'comment-input',
		'contact-us-form',
		'context-menu',
		'copy-button',
		'cron-input',
		'dim-behind',
		'dismissible-message',
        'data-table', 
        // 'drag-drop', 
        'drawer',
        'dropdown-menu',
		'empty-state',
		'fields-builder',
		'file-dropzone',
		'float',
		'frame',
		'frame-nested',
		'h',
		'header',
		'hover-expandable-width',
		'image-cycler',
		'icons',
		'icon-swap',
		'input',
		'input-history',
		'kbd-shortcut',
		'list-item-button',
		'login-form',
		'login-or-register-form',
		'markdown-editor',
		'modal-dialog',
		'modal',
		'nav',
		'notifications',
		'onboarding',
		'otp-input',
		// 'on-outside',
		'pagination',
		'pill',
		'popover',
		'pricing-table',
		'progress',
		'register-form',
		'resizable-width',
		'separator', 
		'skeleton',
		'slider',
		'sliding-panels',
		'spotlight',
		'spinner',
		'split-button',
		'stat',
		'stepper',
		'style-presets',
		'svg-circle',
        'switch', 
		// 'table', 
		'tabbed-menu',
        'thc', 
        'theme-preview', 
        'tooltip',
		'trend-chart',
        'tree',
        'tw-check',
		'user-avatar-menu',
		'wheel-picker',
		'with-side-panel',
		// 'viewport',
		'x'
	].toSorted();
</script>

<div class="p-4">
	<ul class="space-y-2">
		{#each links as link}
			<li>
				<a
					href={link}
					class="block p-2 px-4 rounded-lg bg-neutral-200 dark:bg-neutral-900 hover:text-white hover:bg-neutral-600"
					>{link}</a
				>
			</li>
		{/each}
	</ul>
</div>
